// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proto/init.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FromInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*FromInit_Ready
	//	*FromInit_MapGid
	//	*FromInit_MapUid
	Payload isFromInit_Payload `protobuf_oneof:"payload"`
}

func (x *FromInit) Reset() {
	*x = FromInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromInit) ProtoMessage() {}

func (x *FromInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromInit.ProtoReflect.Descriptor instead.
func (*FromInit) Descriptor() ([]byte, []int) {
	return file_proto_init_proto_rawDescGZIP(), []int{0}
}

func (m *FromInit) GetPayload() isFromInit_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *FromInit) GetReady() *Ready {
	if x, ok := x.GetPayload().(*FromInit_Ready); ok {
		return x.Ready
	}
	return nil
}

func (x *FromInit) GetMapGid() *IdMapping {
	if x, ok := x.GetPayload().(*FromInit_MapGid); ok {
		return x.MapGid
	}
	return nil
}

func (x *FromInit) GetMapUid() *IdMapping {
	if x, ok := x.GetPayload().(*FromInit_MapUid); ok {
		return x.MapUid
	}
	return nil
}

type isFromInit_Payload interface {
	isFromInit_Payload()
}

type FromInit_Ready struct {
	Ready *Ready `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type FromInit_MapGid struct {
	MapGid *IdMapping `protobuf:"bytes,2,opt,name=map_gid,json=mapGid,proto3,oneof"`
}

type FromInit_MapUid struct {
	MapUid *IdMapping `protobuf:"bytes,3,opt,name=map_uid,json=mapUid,proto3,oneof"`
}

func (*FromInit_Ready) isFromInit_Payload() {}

func (*FromInit_MapGid) isFromInit_Payload() {}

func (*FromInit_MapUid) isFromInit_Payload() {}

type Ready struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ready) Reset() {
	*x = Ready{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_proto_init_proto_rawDescGZIP(), []int{1}
}

type IdMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsideId  uint32 `protobuf:"varint,2,opt,name=insideId,proto3" json:"insideId,omitempty"`
	OutsideId uint32 `protobuf:"varint,3,opt,name=outsideId,proto3" json:"outsideId,omitempty"`
}

func (x *IdMapping) Reset() {
	*x = IdMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMapping) ProtoMessage() {}

func (x *IdMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMapping.ProtoReflect.Descriptor instead.
func (*IdMapping) Descriptor() ([]byte, []int) {
	return file_proto_init_proto_rawDescGZIP(), []int{2}
}

func (x *IdMapping) GetInsideId() uint32 {
	if x != nil {
		return x.InsideId
	}
	return 0
}

func (x *IdMapping) GetOutsideId() uint32 {
	if x != nil {
		return x.OutsideId
	}
	return 0
}

// From Runtime
type FromRuntime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*FromRuntime_Start
	Payload isFromRuntime_Payload `protobuf_oneof:"payload"`
}

func (x *FromRuntime) Reset() {
	*x = FromRuntime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromRuntime) ProtoMessage() {}

func (x *FromRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromRuntime.ProtoReflect.Descriptor instead.
func (*FromRuntime) Descriptor() ([]byte, []int) {
	return file_proto_init_proto_rawDescGZIP(), []int{3}
}

func (m *FromRuntime) GetPayload() isFromRuntime_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *FromRuntime) GetStart() *Start {
	if x, ok := x.GetPayload().(*FromRuntime_Start); ok {
		return x.Start
	}
	return nil
}

type isFromRuntime_Payload interface {
	isFromRuntime_Payload()
}

type FromRuntime_Start struct {
	Start *Start `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

func (*FromRuntime_Start) isFromRuntime_Payload() {}

type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_init_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_proto_init_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_proto_init_proto_rawDescGZIP(), []int{4}
}

var File_proto_init_proto protoreflect.FileDescriptor

var file_proto_init_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x76,
	0x31, 0x22, 0xad, 0x01, 0x0a, 0x08, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x2c,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x33, 0x0a, 0x07,
	0x6d, 0x61, 0x70, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x47, 0x69,
	0x64, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06,
	0x6d, 0x61, 0x70, 0x55, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x45, 0x0a, 0x09, 0x49, 0x64,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x69, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x69, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x49,
	0x64, 0x22, 0x46, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_init_proto_rawDescOnce sync.Once
	file_proto_init_proto_rawDescData = file_proto_init_proto_rawDesc
)

func file_proto_init_proto_rawDescGZIP() []byte {
	file_proto_init_proto_rawDescOnce.Do(func() {
		file_proto_init_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_init_proto_rawDescData)
	})
	return file_proto_init_proto_rawDescData
}

var file_proto_init_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_init_proto_goTypes = []any{
	(*FromInit)(nil),    // 0: proto.init.v1.FromInit
	(*Ready)(nil),       // 1: proto.init.v1.Ready
	(*IdMapping)(nil),   // 2: proto.init.v1.IdMapping
	(*FromRuntime)(nil), // 3: proto.init.v1.FromRuntime
	(*Start)(nil),       // 4: proto.init.v1.Start
}
var file_proto_init_proto_depIdxs = []int32{
	1, // 0: proto.init.v1.FromInit.ready:type_name -> proto.init.v1.Ready
	2, // 1: proto.init.v1.FromInit.map_gid:type_name -> proto.init.v1.IdMapping
	2, // 2: proto.init.v1.FromInit.map_uid:type_name -> proto.init.v1.IdMapping
	4, // 3: proto.init.v1.FromRuntime.start:type_name -> proto.init.v1.Start
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_init_proto_init() }
func file_proto_init_proto_init() {
	if File_proto_init_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_init_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FromInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Ready); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*IdMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FromRuntime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_init_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_init_proto_msgTypes[0].OneofWrappers = []any{
		(*FromInit_Ready)(nil),
		(*FromInit_MapGid)(nil),
		(*FromInit_MapUid)(nil),
	}
	file_proto_init_proto_msgTypes[3].OneofWrappers = []any{
		(*FromRuntime_Start)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_init_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_init_proto_goTypes,
		DependencyIndexes: file_proto_init_proto_depIdxs,
		MessageInfos:      file_proto_init_proto_msgTypes,
	}.Build()
	File_proto_init_proto = out.File
	file_proto_init_proto_rawDesc = nil
	file_proto_init_proto_goTypes = nil
	file_proto_init_proto_depIdxs = nil
}
